name: server
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  bcrypt: 1.2.0
  dart_jsonwebtoken: ^3.4.1
  dotenv: ^4.2.0
  mongo_dart: ^0.10.8
  protos:
    path: ../protos

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
